# thekid/cas

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - |
    if php -r 'exit((int)(extension_loaded("sodium") || extension_loaded("openssl")));'; then
      git clone -b stable https://github.com/jedisct1/libsodium.git
      cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
      pecl install libsodium
      echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi

before_script:
  - curl -sSL https://dl.bintray.com/xp-runners/generic/xp-run-8.1.7.sh > xp-run
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth

script:
  - sh xp-run xp.unittest.TestRunner src/test/php
